"""
Domain models for Trading Logic and Strategy Output.

This module holds data structures generated internally by the bot's core logic.
It includes trade candidates (idealized trades), entry/exit signals, and
the current internal state of the rebalancing strategy.

# This model class contains data classes related to  data generated by your bot (trade candidates, signals, strategy state).
"""




from pydantic import BaseModel

class TradeCandidate(BaseModel):
    """An idealized trade calculated by the Rebalancer."""
    symbol: str
    side: str
    amount: float
    price: float

class Asset(BaseModel):
    """An idealized trade calculated by the Rebalancer."""
    symbol: str
    amount: float
    price: float